### PR TITLE
New config file generated from RECO job.

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by Dr15Jones** [comment]
It looks like the yaml files are just intermediate steps for creating reco_displacedjet_busywait.config file. If so, then we shouldn't store them since we can use reco_displacedjet_busywait.config as the base to create any other configuration.

**Comment by Dr15Jones** [comment]
Let's change the file name reco_displacedjet_busywait.config to also state the year and type of input -> reco_2018_data_displacedjet_busywait.config.

**Comment by Dr15Jones** [comment]
Why add edmStreamStallGrapher.py here? Don't you have all the needed changes in the CMSSW version?

**Comment by gartung** [comment]
I just removed it.

**Comment by Dr15Jones** [comment]
The config file has `demo::EventTimesSleepingPassFilter` which should be `demo::EventTimesBusyWaitPassFilter`. That matches what was done in reco_minbias_busywait.config

**Comment by Dr15Jones** [comment]
The filter with the `output` label has as items in its `toGet` of "" and "@EmptyLabel@", which seem incorrect.

**Comment by gartung** [comment]
These resulted from parsing the tracer output. I will put the files used on cmslpc so you can view them.

**Comment by gartung** [comment]
See /uscms_data/d2/gartung/relval/tracer.log

**Comment by Dr15Jones** [comment]
The `output` module does not have the correct structure for its `toGet` entry. That entry should be a list of objects with each object having a `label` and `product` entry. The `output.toGet` has `set([...])` which is not properly json format.

**Comment by gartung** [comment]
I split the input line on ' and pick the second entry.

**Comment by gartung** [comment]
@EmptyLabel@ is set here
https://cmssdt.cern.ch/dxr/CMSSW/source/FWCore/Framework/src/EDConsumerBase.cc#77

**Comment by Dr15Jones** [comment]
I just checked the C++ code, `@EmptyLabel@` is what the framework injects if no label is given to the `consumes` call. In that case, the framework will never match that value so no attempt will be made to retrieve it. Looks like you should filter `@EmptyLabel@` out of the dependencies you generate.

**Comment by Dr15Jones** [comment]
> I split the input line on ' and pick the second entry.

That appears to miss identify items coming from the source, rather than from a module in the job. E.g.
```
  CSCHaloDataProducer/'CSCHaloData' consumes:
    edm::RangeMap<DTChamberId,edm::OwnVector<DTRecSegment4D,edm::ClonePolicy<DTRecSegment4D> >,edm::ClonePolicy<DTRecSegment4D> > 'dt4DSegments' '' ''
...
    edm::TriggerResults 'TriggerResults' '' 'HLT'
```

The `TriggerResults` is from the source (based on the `HLT`) not from this job which also has a `TriggerResults`.

**Comment by Dr15Jones** [comment]
Unfortunately, we do not have separate entries for what data items are coming from the source. For example,
```
FEDRawDataCollection 'rawDataCollector' '' ''
```
Comes from the source and we need that dependency reflected in the configuration. 

It looks like in `reco_minbias_busywait.config` I have several modules with a label of the form '*/HLT' which acts as the stand-ins for the data access from the source. In each case these were set to `threadType` : `ThreadUnsafe` in order to keep them from running concurrently.

**Comment by Dr15Jones** [comment]
In the config file, for the 'output' module's 'toGet' parameter we have
```
{"label": "siPixelClusters",
  "product": ["siPixelClustersPreSplitting",
                      "firstStepPrimaryVerticesPreSplitting",
                      "jetsForCoreTrackingPreSplitting"]},
```

but as far as I can tell, the `"product"` should just be an empty string, not a list.

**Comment by Dr15Jones** [comment]
Do we know why we are only getting time down to the millisecond? Does the StallMonitor only go to that level?

**Comment by Dr15Jones** [comment]
I checked and the StallMonitor is only recording at the millisecond granularity. We should change that to microseconds to capture more precise info for this purpose.

**Comment by Dr15Jones** [comment]
@gartung which modules did not have event times in your measurement?

**Comment by gartung** [comment]
The ones with all eventTimes entries exactly equal to 0.0

**Comment by gartung** [comment]
gedElPFIsoDepositCharged for example

**Comment by Dr15Jones** [comment]
@gartung where is the original log file you used to get the info?

**Comment by gartung** [comment]
According to the RECO job report these are the branches read from the RAW data files
`<Branches>
  <Branch>FEDRawDataCollection_rawDataCollector__LHC.</Branch>
  <Branch>GlobalObjectMapRecord_hltGtStage2ObjectMap__HLT.</Branch>
  <Branch>edmTriggerResults_TriggerResults__HLT.</Branch>
  <Branch>triggerTriggerEvent_hltTriggerSummaryAOD__HLT.</Branch>
</Branches>
`

**Comment by Dr15Jones** [comment]
@gartung This is looking pretty good. The only item of note is sometimes the same label is used multiple times in the 'toGet'
```json
            "toGet": [
               {
                  "product": "", 
                  "label": "ecalDigis"
               }, 
               {
                  "product": "", 
                  "label": "ecalDigis"
               }, 
               {
                  "product": "", 
                  "label": "ecalDigis"
               }, 
               {
                  "product": "", 
                  "label": "ecalDigis"
               }, 
               {
                  "product": "", 
                  "label": "ecalDigis"
               }, 
               {
                  "product": "", 
                  "label": "ecalDigis"
               }, 
               {
                  "product": "", 
                  "label": "ecalDigis"
               }, 
               {
                  "product": "", 
                  "label": "ecalDigis"
               }
            ], 
            "threadType": "ThreadSafeBetweenInstances", 
            "@label": "ecalDetIdToBeRecovered", 
            "@type": "demo::EventTimesBusyWaitProducer"
         }, 
```

**Comment by gartung** [comment]
@Dr15Jones All of these modules have the same label, but the third field is different. I removed the duplicates. 

 I made a network graph of from the consumes dictionaries and found the list of all node in a tree rooted at RECOoutput. This produced a config but there were still dependencies with no event times.
I finally got a working config by looking at what modules are reported as constructed in tracer.log and only adding dependencies if they were constructed. 
This is the list of consumed dependencies that were not constructed.

module label bunchSpacingProducer dependency label addPileupInfo not constructed
module label multi5x5SuperClustersCleaned dependency label multi5x5BasicClusters not constructed
module label interestingGedEgammaIsoESDetId dependency label particleFlowClusterECALRemade not constructed
module label uncleanedOnlyElectronSeeds dependency label dummyVertices not constructed
module label ecalDrivenElectronSeeds dependency label dummyVertices not constructed
module label multi5x5SuperClustersUncleaned dependency label multi5x5BasicClusters not constructed

**Comment by Dr15Jones** [comment]
I looked at `bunchSpacingProducer` and it turns out it only actually reads the 'addPileupInfo' if it is not real data

https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/RecoLuminosity/LumiProducer/plugins/BunchSpacingProducer.cc#L88

**Comment by Dr15Jones** [comment]
The modules with labels `multi5x5SuperClustersCleaned` and `multi5x5SuperClustersUncleaned` are of type Multi5x5SuperClusterProducer and only read some of their 'consumes' based on a configuration parameters:
https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/RecoEcal/EgammaClusterProducers/src/Multi5x5SuperClusterProducer.cc#L82

so they say the consume something even if they never actually do.

**Comment by Dr15Jones** [comment]
The module with label `interestingGedEgammaIsoESDetId` is of type `EgammaIsoESDetIdCollectionProducer` and it checks for the validity of data it gets from the event and will continue even it did not get it:
https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/RecoEgamma/EgammaIsolationAlgos/plugins/EgammaIsoESDetIdCollectionProducer.cc#L74

**Comment by gartung** [comment]
The sleeping producer config produces this on my 4HT core cpu:
`
TBB:# threads:8 # simultaneous events:1 total # events:100 cpu time:122.128 real time:438.229 events/sec:0.228191
`

**Comment by gartung** [comment]
This is the TimeReport from the RECO job

 Time Summary:
 - Min event:   3.55226
 - Max event:   35.1318
 - Avg event:   12.6466
 - Total loop:  348.028
 - Total init:  42.3557
 - Total job:   392.397
 - EventSetup Lock:   212.079
 - EventSetup Get:   40.8856
 Event Throughput: 0.574666 ev/s

**Comment by gartung** [comment]
On cmsdev15.cern.ch I get the following throughput with the sleeping producer
TBB:# threads:1 # simultaneous events:1 total # events:100 cpu time:0.98885 real time:1107.31 events/sec:0.0903089  = 11.0731057515 sec avg event

**Comment by gartung** [comment]
With 200 events on my desktop
TBB:# threads:8 # simultaneous events:8 total # events:200 cpu time:3.68386 real time:293.1 events/sec:0.682361

**Pull request merged**
